services:
  mongo:
    image: mongo:7.0
    container_name: mongodb_replica
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"]
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: